version: '3.5'
services:

  redis-cluster:
    image: 'redis:7.0.2'
    command: redis-cli --cluster create 172.29.0.31:6373 172.29.0.32:6374 172.29.0.33:6375 172.29.0.34:6376 172.29.0.35:6377 172.29.0.36:6378 --cluster-replicas 1 --cluster-yes
    networks:
      app_subnet:
        ipv4_address: 172.29.0.30
    depends_on:
      redis-node-1:
        condition: service_healthy
      redis-node-2:
        condition: service_healthy
      redis-node-3:
        condition: service_healthy
      redis-node-4:
        condition: service_healthy
      redis-node-5:
        condition: service_healthy
      redis-node-6:
        condition: service_healthy

  redis-node-1:
    image: 'redis:7.0.2'
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6373", "--raw", "incr", "ping" ]    
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6373:6373'
    volumes:
      - redis-node-1-data:/var/lib/redis
      - ./redis-node-1.conf:/usr/local/etc/redis/redis.conf
      - ./module-oss.so:/usr/lib/redis/module-oss.so
    networks:
      app_subnet:
        ipv4_address: 172.29.0.31

  redis-node-2:
    image: 'redis:7.0.2'
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6374", "--raw", "incr", "ping" ]    
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6374:6374'
    volumes:
      - redis-node-2-data:/var/lib/redis
      - ./redis-node-2.conf:/usr/local/etc/redis/redis.conf
      - ./module-oss.so:/usr/lib/redis/module-oss.so
    networks:
      app_subnet:
        ipv4_address: 172.29.0.32

  redis-node-3:
    image: 'redis:7.0.2'
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6375", "--raw", "incr", "ping" ]    
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6375:6375'
    volumes:
      - redis-node-3-data:/var/lib/redis
      - ./redis-node-3.conf:/usr/local/etc/redis/redis.conf
      - ./module-oss.so:/usr/lib/redis/module-oss.so
    networks:
      app_subnet:
        ipv4_address: 172.29.0.33

  redis-node-4:
    image: 'redis:7.0.2'
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6376", "--raw", "incr", "ping" ]    
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6376:6376'
    volumes:
      - redis-node-4-data:/var/lib/redis
      - ./redis-node-4.conf:/usr/local/etc/redis/redis.conf
      - ./module-oss.so:/usr/lib/redis/module-oss.so
    networks:
      app_subnet:
        ipv4_address: 172.29.0.34

  redis-node-5:
    image: 'redis:7.0.2'
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6377", "--raw", "incr", "ping" ]    
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6377:6377'
    volumes:
      - redis-node-5-data:/var/lib/redis
      - ./redis-node-5.conf:/usr/local/etc/redis/redis.conf
      - ./module-oss.so:/usr/lib/redis/module-oss.so
    networks:
      app_subnet:
        ipv4_address: 172.29.0.35

  redis-node-6:
    image: 'redis:7.0.2'
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6378", "--raw", "incr", "ping" ]    
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 10
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6378:6378'
    volumes:
      - redis-node-6-data:/var/lib/redis
      - ./redis-node-6.conf:/usr/local/etc/redis/redis.conf
      - ./module-oss.so:/usr/lib/redis/module-oss.so
    networks:
      app_subnet:
        ipv4_address: 172.29.0.36

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
        